import { Verse } from '@/types';

export const DAILY_VERSES: Verse[] = [
  { reference: 'Philippians 4:13', text: 'I can do all things through Christ which strengtheneth me.' },
  { reference: 'Isaiah 40:31', text: 'But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.' },
  { reference: '1 Corinthians 9:24', text: 'Know ye not that they which run in a race run all, but one receiveth the prize? So run, that ye may obtain.' },
  { reference: '2 Timothy 4:7', text: 'I have fought a good fight, I have finished my course, I have kept the faith.' },
  { reference: 'Hebrews 12:1', text: 'Let us run with patience the race that is set before us.' },
  { reference: 'Joshua 1:9', text: 'Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.' },
  { reference: 'Psalm 18:32', text: 'It is God that girdeth me with strength, and maketh my way perfect.' },
  { reference: 'Psalm 18:33', text: 'He maketh my feet like hinds\' feet, and setteth me upon my high places.' },
  { reference: 'Psalm 18:39', text: 'For thou hast girded me with strength unto the battle.' },
  { reference: '2 Samuel 22:30', text: 'For by thee I have run through a troop: by my God have I leaped over a wall.' },
  { reference: 'Proverbs 24:10', text: 'If thou faint in the day of adversity, thy strength is small.' },
  { reference: 'Romans 8:37', text: 'Nay, in all these things we are more than conquerors through him that loved us.' },
  { reference: '1 Corinthians 15:57', text: 'But thanks be to God, which giveth us the victory through our Lord Jesus Christ.' },
  { reference: 'Colossians 3:23', text: 'And whatsoever ye do, do it heartily, as to the Lord, and not unto men.' },
  { reference: 'Galatians 6:9', text: 'And let us not be weary in well doing: for in due season we shall reap, if we faint not.' },
  { reference: 'Ecclesiastes 9:11', text: 'The race is not to the swift, nor the battle to the strong.' },
  { reference: '1 Samuel 17:47', text: 'For the battle is the Lord\'s.' },
  { reference: 'Deuteronomy 31:6', text: 'Be strong and of a good courage, fear not, nor be afraid of them: for the Lord thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.' },
  { reference: 'Psalm 144:1', text: 'Blessed be the Lord my strength, which teacheth my hands to war, and my fingers to fight.' },
  { reference: 'Isaiah 41:10', text: 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee.' },
  { reference: 'Ephesians 6:10', text: 'Be strong in the Lord, and in the power of his might.' },
  { reference: 'Habakkuk 3:19', text: 'The Lord God is my strength, and he will make my feet like hinds\' feet.' },
  { reference: 'Psalm 60:12', text: 'Through God we shall do valiantly.' },
  { reference: '1 Chronicles 16:11', text: 'Seek the Lord and his strength, seek his face continually.' },
  { reference: 'Psalm 28:7', text: 'The Lord is my strength and my shield.' },
  { reference: 'Nehemiah 8:10', text: 'The joy of the Lord is your strength.' },
  { reference: 'Romans 5:3', text: 'We glory in tribulations also: knowing that tribulation worketh patience.' },
  { reference: 'James 1:12', text: 'Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life.' },
  { reference: 'Hebrews 10:35', text: 'Cast not away therefore your confidence, which hath great recompence of reward.' },
  { reference: 'Proverbs 3:5-6', text: 'Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.' },
  { reference: 'Psalm 37:23', text: 'The steps of a good man are ordered by the Lord.' },
];
